name: base
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.8
  - cudatoolkit=10.1.243
  - pytorch=1.7.1
  - torchvision=0.8.2
  - pytorch-lightning=1.3.8
  - onnxruntime=1.7.2
  - scikit-learn
  - pandas
  - numpy
  - h5py
  - pip
  - pip:
    - git+https://github.com/joefutrelle/pyifcb.git